name = "pyr-p7c-SH-L"
entire_sequence ="MSPEDENQALEQEIAQLEQEIAALEQKNAQLKYGRGDGSPEDEIKELEEEIKELEWKNEELKRKNEELKRGRGDGDIEQELERAKQSIEELEREVNQERSRMQYLQTRLSRGDGSPEDKNEELKREIKELEWENEELERKIEELKRGRGDGELEELERELQEIEEQLEQLQWKAQERKEKLEQLKERGDGSPEDKIEELKRKIEELKWENEELERENEELERGRGDGSPEDRMKQLEDKVEELERKNYHLENEVERLKKEVRGDGSPEDKNAQLKEKIAALKEKIQQLKEENQALEYGRGDGELEELERELQEIEEQLEQLQWKAQERKEKLEQLKERGDGSPEDEIQALEEENAQLEQENAALEEEIAQLEYGRGDGSPEDEIKELEWKNEELKREIKELEEKNEELKRGRGDGDIEQELERAKQSIEELEREVNQERSRMQYLQTRLSRGDGSPEDRMKQLEDKVEELERKNYHLENEVERLKKEVRGDGSPEDKIEELKRENEELEWKIEELKRENEELEKGRGDGSPEDENEKLEEKIWELKRKNEELKREIKELEEGRGDGSPEDKIAQLKEKNAALKEKNQQLKEKIQALKYGLEHHHHHHHH"
segments = """
M
SPED ENQALEQ EIAQLEQ EIAALEQ KNAQLKY G  |P11SH
RGDG
SPED EIKELEE EIKELEW KNEELKR KNEELKR G  |P3SH
RGDG
DIEQ ELERAKQ SIEELER EVNQERS RMQYLQT RLS  |BCRmSH
RGDG
SPED KNEELKR EIKELEW ENEELER KIEELKR G  |P6SH
RGDG
ELEELER ELQEIEE QLEQLQW KAQERKE KLEQLKE |APHshE
RGDG
SPED KIEELKR KIEELKW ENEELER ENEELER G  |P4SH
RGDG
SPED RMKQLED KVEELER KNYHLEN EVERLKK EV |GCNH3
RGDG
SPED KNAQLKE KIAALKE KIQQLKE ENQALEY G  |P12SH
RGDG
ELEELER ELQEIEE QLEQLQW KAQERKE KLEQLKE |APHshE
RGDG
SPED EIQALEE ENAQLEQ ENAALEE EIAQLEY G  |P1SH
RGDG
SPED EIKELEW KNEELKR EIKELEE KNEELKR G  |P7SH
RGDG
DIEQ ELERAKQ SIEELER EVNQERS RMQYLQT RLS  |BCRmSH
RGDG
SPED RMKQLED KVEELER KNYHLEN EVERLKK EV |GCNH3
RGDG
SPED KIEELKR ENEELEW KIEELKR ENEELEK G  |P8SH
RGDG
SPED ENEKLEE KIWELKR KNEELKR EIKELEE G  |P5SH
RGDG
SPED KIAQLKE KNAALKE KNQQLKE KIQALKY G  |P2SH
LEHHHHHHHH
"""

pairs = """
- pair : APHshE:APHshE
  type : A  
  chains : A:B
  template : APH.pdb  

- pair : BCRmSH:BCRmSH
  type : A  
  chains : A:B
  template : BCR.pdb  

- pair : P1SH:P2SH
  type : P  
  chains : A:B
  template : p1_p2.pdb  

- pair : P3SH:P4SH
  type : P  
  chains : A:B
  template : p3_p4.pdb  

- pair : P5SH:P6SH
  type : P  
  chains : A:B
  template : p5_p6.pdb    

- pair : GCNH3:GCNH3
  type : P  
  chains : A:B
  template : GCN.pdb      

- pair : P7SH:P8SH
  type : P  
  chains : A:B
  template : p7_p8.pdb        

- pair : P7SH:P8SH
  type : P  
  chains : A:B
  template : p7_p8.pdb        

- pair : P11SH:P12SH
  type : P  
  chains : A:B
  template : p11_p12.pdb        
"""   


if __name__ == "__main__":
    import ppmod.make_json as mj   
    pairs = mj.load_pairs(pairs)    
    mj.generate_json(name, entire_sequence, segments, pairs)