name = "pyr-p1b-SN-N5"
entire_sequence = "MLEEELKQLEEELQAIEEQLAQLQWKAQARKEKLAQLKEKLGSGPGSPEDENSQLEEKISQLKQKNSELKEEIQQLEYGSGPGSPEDEIRQLEQENSQLERENQRLEQEIYQLERGSGPGQLEDKVEELLSKNYHLENEVERLKKLVGGSGPGLEEELKQLEEELQAIEEQLAQLQWKAQARKEKLAQLKEKLGSGPGSPEDEIQQLEEKNSQLKQEISQLEEKNQELKYGSGPGQLEDKVEELLSKNYHLENEVERLKKLVGGSGPGSPEDKNSELKEEIQQLEEENQQLEEKISELKYGSGPGDIEQELERAKESIRRLEQEVNQERSRMQYLQTLLEKGSGPGSPEDEIQQLEEEISQLEQKNSELKEKNQELKYGSGPGSPEDKISELKEENQQLEQKIQQLKEENSQLEYGSGPGSPEDENQSLEQKNSQLKQEISQLEQEIQQLEYGSGPGDIEQELERAKESIRRLEQEVNQERSRMQYLQTLLEKGSGPGSPEDKIEELKEKNSQLKEKNEELKQKIYELKEGSGPGSPEDKNSQLKEENSQLEEKIEQLKEKIQELKYGSGPGSPEDKISQLKEKIQQLKQENQQLEEENSQLEYLEHHHHHHHH"
segments = """

M
LEE ELKQLEE ELQAIEE QLAQLQW KAQARKE KLAQLKE KL  |APHshmSN
GSGPG
SPED ENSQLEE KISQLKQ KNSELKE EIQQLEY  |P5mSN
GSGPG
SPED EIRQLEQ ENSQLER ENQRLEQ EIYQLER  |P1mSN
GSGPG
QLED KVEELLS KNYHLEN EVERLKK LVG  |GCNshmSN
GSGPG
LEE ELKQLEE ELQAIEE QLAQLQW KAQARKE KLAQLKE KL  |APHshmSN
GSGPG
SPED EIQQLEE KNSQLKQ EISQLEE KNQELKY  |P7mSN
GSGPG
QLED KVEELLS KNYHLEN EVERLKK LVG  |GCNshmSN
GSGPG
SPED KNSELKE EIQQLEE ENQQLEE KISELKY  |P6mSN
GSGPG
DIEQ ELERAKE SIRRLEQ EVNQERS RMQYLQT LLEK |BCRmSN
GSGPG
SPED EIQQLEE EISQLEQ KNSELKE KNQELKY  |P3mSN
GSGPG
SPED KISELKE ENQQLEQ KIQQLKE ENSQLEY  |P8mSN
GSGPG
SPED ENQSLEQ KNSQLKQ EISQLEQ EIQQLEY  |P9mSN
GSGPG
DIEQ ELERAKE SIRRLEQ EVNQERS RMQYLQT LLEK |BCRmSN
GSGPG
SPED KIEELKE KNSQLKE KNEELKQ KIYELKE  |P2mSN
GSGPG
SPED KNSQLKE ENSQLEE KIEQLKE KIQELKY  |P10mSN
GSGPG
SPED KISQLKE KIQQLKQ ENQQLEE ENSQLEY  |P4mSN
LEHHHHHHHH
"""

pairs = """
- pair : APHshmSN:APHshmSN
  type : A  
  chains : A:B
  template : APH.pdb  
  color : #D62728

- pair : BCRmSN:BCRmSN
  type : A  
  chains : A:B
  template : BCR.pdb  
  color : #2CA02C

- pair : P1mSN:P2mSN
  type : P  
  chains : A:B
  template : p1_p2.pdb  
  color : #E377C2

- pair : P3mSN:P4mSN
  type : P  
  chains : A:B
  template : p3_p4.pdb  
  color : #1F77B4

- pair : P5mSN:P6mSN
  type : P  
  chains : A:B
  template : p5_p6.pdb  
  color : #FF7F0E
  

- pair : GCNshmSN:GCNshmSN
  type : P  
  chains : A:B
  template : GCN.pdb 
  color : #8C564B     

- pair : P7mSN:P8mSN
  type : P  
  chains : A:B
  template : p7_p8.pdb        
  color : #9467BD

- pair : P9mSN:P10mSN
  type : P  
  chains : A:B
  template : p9_p10.pdb
  color : #BCBD22        
"""   


if __name__ == "__main__":
    import ppmod.make_json as mj   
    pairs = mj.load_pairs(pairs)    
    mj.generate_json(name, entire_sequence, segments, pairs)